#!/usr/bin/env python3
"""
Provenance — NPC UUID Registry Updater
=======================================
Uses only the Python standard library.

WORKFLOW
--------
1. Add NPCs to _npcs/npcs/registry.json (all fields except taterzen_uuid).

2. Generate the in-game export function:
       python scripts/minecraft/update_uuids.py generate

3. Reload the datapack in Minecraft:
       /reload

4. Run the export function in-game as an operator:
       /function luminacion:admin/export_npc_uuids

5. Parse the log and update the registry:
       python scripts/minecraft/update_uuids.py update --log "C:/path/to/logs/latest.log"

   If you do not know your log path, run:
       python scripts/minecraft/update_uuids.py locate-log
"""

import argparse
import json
import re
import struct
import sys
import uuid
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths (relative to project root, two levels above /scripts/minecraft)
# ---------------------------------------------------------------------------
ROOT          = Path(__file__).resolve().parent.parent.parent
REGISTRY_PATH = ROOT / "_npcs" / "npcs" / "registry.json"
FUNCTION_PATH = ROOT / "data" / "luminacion" / "functions" / "admin" / "export_npc_uuids.mcfunction"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_registry() -> dict:
    with open(REGISTRY_PATH, encoding="utf-8") as f:
        return json.load(f)


def save_registry(data: dict) -> None:
    with open(REGISTRY_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def int_array_to_uuid(ints: list[int]) -> str:
    """
    Convert a 4-element Minecraft UUID int array to a UUID string.

    Minecraft stores UUIDs as four signed 32-bit big-endian integers.
    e.g. [I; -12345, 67890, -11111, 22222]  →  "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    """
    raw = b"".join(struct.pack(">i", i) for i in ints)
    return str(uuid.UUID(bytes=raw))


def active_npcs(registry: dict) -> dict:
    """Return NPC entries, skipping template/comment keys."""
    return {
        k: v for k, v in registry.get("npcs", {}).items()
        if not k.startswith("_")
    }


# ---------------------------------------------------------------------------
# Command: generate
# ---------------------------------------------------------------------------

def cmd_generate(registry: dict) -> None:
    """Write the in-game export function from the current registry."""
    npcs = active_npcs(registry)

    if not npcs:
        print("No NPCs in registry yet. Add entries to _npcs/npcs/registry.json first.")
        sys.exit(1)

    lines = [
        "# Provenance — NPC UUID Export",
        "# Auto-generated by scripts/minecraft/update_uuids.py — do not edit by hand.",
        "# Run in-game as an operator, then run: python scripts/minecraft/update_uuids.py update --log <path>",
        "",
    ]

    for key, npc in npcs.items():
        name = npc.get("display_name", "").strip()
        if not name:
            print(f"  WARNING: '{key}' has no display_name — skipping.")
            continue
        lines += [
            f"# {key}",
            # 'say' outputs to chat AND to logs/latest.log, unlike tellraw
            f'say PROVENANCE_NPC_EXPORT|{key}|{name}',
            f'data get entity @e[name={name},limit=1] UUID',
            "",
        ]

    lines += [
        'say PROVENANCE_NPC_EXPORT|DONE|all NPCs exported',
        'tellraw @s [{"text":"[Provenance] ","color":"gold","bold":true},{"text":"Export done. Now run: python scripts/minecraft/update_uuids.py update --log <path>"}]',
    ]

    FUNCTION_PATH.parent.mkdir(parents=True, exist_ok=True)
    FUNCTION_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated: {FUNCTION_PATH.relative_to(ROOT)}")
    print()
    print("Next steps:")
    print("  1. /reload  (in Minecraft)")
    print("  2. /function luminacion:admin/export_npc_uuids  (in Minecraft, as operator)")
    print("  3. python scripts/minecraft/update_uuids.py update --log \"<path/to/logs/latest.log>\"")


# ---------------------------------------------------------------------------
# Command: update
# ---------------------------------------------------------------------------

# Matches:  [15:23:45] [Server thread/INFO]: [PlayerName] PROVENANCE_NPC_EXPORT|key|name
MARKER_RE = re.compile(r"PROVENANCE_NPC_EXPORT\|([^|]+)\|(.+)")

# Matches:  [15:23:45] [Server thread/INFO]: EntityName has the following entity data: [I; -1, 2, -3, 4]
UUID_RE    = re.compile(r"has the following entity data: \[I; (-?\d+), (-?\d+), (-?\d+), (-?\d+)\]")


def cmd_update(log_path: str, registry: dict) -> None:
    """Parse the log file and update taterzen_uuid in the registry."""
    path = Path(log_path)
    if not path.exists():
        print(f"Log file not found: {path}")
        sys.exit(1)

    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()

    pending_key = None
    updates: dict[str, str] = {}

    for line in lines:
        marker = MARKER_RE.search(line)
        if marker:
            key = marker.group(1)
            if key == "DONE":
                pending_key = None
            else:
                pending_key = key
            continue

        if pending_key:
            uuid_match = UUID_RE.search(line)
            if uuid_match:
                ints = [int(x) for x in uuid_match.groups()]
                updates[pending_key] = int_array_to_uuid(ints)
                pending_key = None

    if not updates:
        print("No UUID data found in the log.")
        print("Make sure you ran /function luminacion:admin/export_npc_uuids in-game first.")
        sys.exit(1)

    npcs = registry.setdefault("npcs", {})
    for key, npc_uuid in updates.items():
        if key in npcs:
            npcs[key]["taterzen_uuid"] = npc_uuid
            print(f"  {key}: {npc_uuid}")
        else:
            print(f"  WARNING: '{key}' found in log but not in registry — skipped.")

    save_registry(registry)
    print()
    print(f"Registry updated: {REGISTRY_PATH.relative_to(ROOT)}")


# ---------------------------------------------------------------------------
# Command: locate-log
# ---------------------------------------------------------------------------

def cmd_locate_log() -> None:
    """Print likely Minecraft log file locations for this machine."""
    import os
    candidates = []

    if sys.platform == "win32":
        appdata = Path(os.environ.get("APPDATA", "~")).expanduser()
        candidates += [
            appdata / ".minecraft" / "logs" / "latest.log",
        ]
    elif sys.platform == "darwin":
        candidates += [
            Path("~/Library/Application Support/minecraft/logs/latest.log").expanduser(),
        ]
    else:
        candidates += [
            Path("~/.minecraft/logs/latest.log").expanduser(),
        ]

    print("Likely Minecraft log locations:")
    for c in candidates:
        exists = "  [FOUND]" if c.exists() else "  [not found]"
        print(f"  {c}{exists}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Provenance — NPC UUID registry updater",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("generate", help="Generate the in-game export function from the registry")

    update_p = sub.add_parser("update", help="Parse the game log and write UUIDs into the registry")
    update_p.add_argument("--log", required=True, metavar="PATH", help="Path to logs/latest.log")

    sub.add_parser("locate-log", help="Print likely Minecraft log file locations")

    args = parser.parse_args()

    if args.command == "locate-log":
        cmd_locate_log()
        return

    registry = load_registry()

    if args.command == "generate":
        cmd_generate(registry)
    elif args.command == "update":
        cmd_update(args.log, registry)


if __name__ == "__main__":
    main()
